### ISSUE TITLE
npm依赖问题

### ISSUE THREAD

**Issue by SaltFish001** [qld-cf/electron-common-react-tpl#1]
```
yp-rider
```
这个依赖项在npm上不存在，我估计是你私有npm库里的。搜了下好像也没有引用的地方。建议删除 @qld-cf

**Comment by qld-cf** [comment]
> ```
> yp-rider
> ```
> 
> 这个依赖项在npm上不存在，我估计是你私有npm库里的。搜了下好像也没有引用的地方。建议删除 @qld-cf

收到 已处理
